---
sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: --without system_tests development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=build DEPLOY_TO_FORGE=yes
notifications:
  email: false
deploy:
  provider: puppetforge
  user: icann
  password:
    secure: "XP7NlCzBEDoMGMG6UVLzUv3vKk9RJDAiB4Ty9jra798ULGoAiJTIXgC4LUrz0XhIZXGW5HeUj/E2XFhgMsSNWtyBac7yywZQjqbxC6r6DbqcxbLnE/TBWd/RTfiGYZYDODXW00S55/Uai/ZEvrk5gWp4YfRpUSQR2jXi05w7NmtDfOFWWx9P56qmFs5vlihqQkNaTc55V1TLaNzESrSeoa2cEVK1w1re16VqR5dJnUQcnp9N5/3FZ/X0p5jdSkGx/jHNt1awT+Sh72Szf2dGpRNn7OQuSeA/8DaWodkPFtO+xw5UXGRbgH3v0fFxxnoeZdrNdfIzfXg/p6UImWixYqCxxEghSV515ACgpoUY1aMcL2f6CKiWyjYABG/GsBSgBTmmbAY6sMJrIY5rHXeYfCy5+wqOzMbWZMC1qwSB3i/bzZbX8UzgW8W9Ljj97eQE+nLUKC0mStKd9fZa/hljFMwynGY2r9+bOhX9H05kmhf7gJD0YDxTspXAc27mG81NuPe1VlYbwvGW8GkKP1nFG4AxkSkAVOYXLDSTX3ed8G0IdsxtUrx8lktmc3pS7Iq2GQa/8evdS59XJEQkanQaz7yiblf/YqMyTGR2+R5NBjuz12qG5fEs/BOSXTKBn6rZcSN78ipfVibhbUvPFsNq75xxXWCh/aw2IzO3VyewmME="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
